[workspace]

members = [
    "frontend",
    "api",
    "data",
    "d2-client",
    "armor",
    "crawler"
]

[build]
rustflags = ["-C", "target-cpu=native"]

[profile.release]
strip = true
lto = true
opt-level = 3
# opt-level = "s"
