[workspace]

members = [
    "frontend",
    "api",
    "data",
    "d2-client",
    "armor",
    "crawler",
    "d2-api",
    "openapi-generator"
]

[profile.release]
# strip = true
# lto = true
opt-level = 3
debug = true
# opt-level = "s"
