[package]
name = "openapi-generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codegen = "0.2.0"
genco = "0.17.3"
serde = { version = "1.0", features = ["serde_derive"] }
serde_json = "1.0"
